### ISSUE TITLE
add captions below plots

### ISSUE THREAD

**Issue by bbest** [marinebon/infographiq#1]
in plot_timeseries() or create_site()?

**Comment by 7yl4r** [comment]
Frank suggested this last week too. Info that might go in the captions:

1.    what the plot shows
2.   where the data is coming from
3.    links for more information?

I would like to get enough information together to mockup a single modal before deciding how to implement this technically.

first up, let's identify which modal (aka one silhouette within the corals page) we want to use to explore this concept. @mhepner90 : do you have a suggestion here?

**Comment by mhepner90** [comment]
@7yl4r Herbivores would be a good one to start with. 

I am thinking we should add a plot caption with 2-3 sentences explaining what the plot shows and a link to the [fk_infographic_data.Rmd](https://github.com/marinebon/info-fk/blob/master/prep/fk_infographic_data.Rmd) so the user can see how it was calculated as well as information about where the data is coming from.

**Comment by 7yl4r** [comment]
I don't see Herbivores on the info-fk corals page.

**Comment by 7yl4r** [comment]
This functionality now working at the modal-level (not for each plot individually). Click the parrotfish on [corals](https://marinebon.github.io/info-fk/corals.html) to view.

**Comment by 7yl4r** [comment]
let's call this closed by the addition of modal-level captions, and we'll open another if we want to get to the caption-per-plot level.
