### ISSUE TITLE
biomass, percent coverage, abundance

### ISSUE THREAD

**Issue by reikopm** [marinebon/infographiq#24]
Our phytoplankton measurements are converted to mg carbon m-3, which we have referred to as biomass.

How do you calculate your biomass and percent coverage? 

Should I be calling our phytoplankton measurements 'abundance'?

**Comment by 7yl4r** [comment]
I don't know much about this, but I believe that @mhepner90 's scripts in [mhepner90/RVC/SDG14](https://github.com/mhepner90/RVC/blob/master/SDG14/MBON_SDG14_FKNMS_classification.Rmd) were used to calculate those.
