### ISSUE TITLE
info-mb web page says "Florida Keys"

### ISSUE THREAD

**Issue by reikopm** [marinebon/infographiq#25]
I've searched where to change the web page titles from "Florida Keys" to "Monterey Bay" but I cannot find it.  Can you help?

**Comment by 7yl4r** [comment]
Where are you seeing "Florida Keys"? At https://marinebon.github.io/info-mb/ I see "Monterey Bay".

**Comment by reikopm** [comment]
Hello Tylar,

Thanks for looking into this. I was having git problems last week, but this morning was able to update the files. Can you take another look?

**Comment by 7yl4r** [comment]
Ah, okay. Now I see it. I'm not sure of the cause but my first guess is that maybe the `rmd` and `docs` folders are not overwriting as we expect them to. Can you try removing them entirely so we for sure start from scratch and then running `create_info_site` again?

**Comment by bbest** [comment]
Yes, that's it @7yl4r, per suggested [marinebon/info-mb/`create_info_site.R`](https://github.com/marinebon/info-mb/blob/master/create_info_site.R)

```r
# devtools::install_github('marinebon/infographiq')
infographiq::create_info_site(
  site_title = "Monterey Bay Infographics",
  render_modals = T)
```
