### ISSUE TITLE
rm error msg in modal with no plots

### ISSUE THREAD

**Issue by reikopm** [marinebon/infographiq#30]
Jennifer wanted text and a link to the SB LTER site for the kelp canopy icon, so there is no graph. I added the text to the modal caption which appears with error messages. Can these be removed?
![kelp_canopy_errors](https://user-images.githubusercontent.com/1767453/31249758-64c8fe8c-a9cd-11e7-866a-1c138a60a4de.JPG)

**Comment by 7yl4r** [comment]
fun R tidbit of the day: `for (i in 1:0)` runs twice because of decrementing range indexing, so all this needed was an extra `if(nrow(data) > 0)`

```r
> for(i in 1:0){ print(".")}
[1] "."
[1] "."
```
