### ISSUE TITLE
document overview of repos - libraries & instances across marinebon/noaa-onms/noaa-iea

### ISSUE THREAD

**Issue by bbest** [marinebon/infographiq#4]
Ok, I'm liking this architecture. I think we should put this into the **infographiq** documentation.

- **marinebon/**
  Marine Biodiversity Observation Network (IOOS/NOAA/NASA) support
  - [**infographiqJS**](https://marinebon.org/infographiqJS): core JS-only (without R or other JS libraries)
    * _**templates**_: [infographiq_example.zip](https://github.com/marinebon/infographiqJS/blob/main/infographiq_example.zip) (HTML/JS only)
  - [**infographiqR**](https://marinebon.org/infographiqR): R helper functions 
    * _**templates**_: TODO: marinebon/infographiqR#64
  - [**infographiq**](https://marinebon.org/infographiq): documentation showing all the interoperable elements and scenarios
- **noaa-onms/**:
  NOAA's Office of National Marine Sanctuary
  - [**onmsR**](https://noaa-onms.github.io/onmsR): helper functions for dataset-specific wrangling and visualization
  - [**cinms**](https://noaa-onms.github.io/cinms): _**instance**_ of infographiqR website for Channel Islands
  - [**ocnms**](https://noaa-onms.github.io/ocnms): _**instance**_ of infographiqR website for Olympic Coast
  - [**sanctsound**](https://noaa-onms.github.io/ocnms): _**instance**_ of infographiqR website for Sanctuaries & Sound
- **noaa-iea/**
  NOAA's Integrated Ecosystem Assessment program
  - [**plotJS-extra**](https://github.com/noaa-iea/plotJS-extra): extra JS plot with IEA style
  - [**fk-esr-info**](https://noaa-iea.github.io/fk-esr-info/infographic.html):_**instance**_ of infographiqJS website
  - [**ak-info**](https://noaa-iea.github.io/ak-info):_**instance**_ of infographiqJS website
  - [**indicators-table**](https://github.com/noaa-iea/indicators-table)

This hierarchy was also visualized by Jenn:

![image.png](https://images.zenhubusercontent.com/53c976bbe6799ebe48001049/74724b08-9608-4499-ab9f-7fed14182c74)

**Comment by bbest** [comment]
And a note about how this interoperate with credit due, eg for [noaa-iea/fk-esr-info](https://noaa-iea.github.io/fk-esr-info/infographic.html):

- Click on **Infographic Credit**:
  ![Screen Shot 2021-06-25 at 10 18 12 AM](https://user-images.githubusercontent.com/2837257/123462240-e779cb80-d59e-11eb-9546-3efa2dcb18a1.png)

- Note credit to **people** and **tools** (associated with organizations):
  ![Screen Shot 2021-06-25 at 10 19 09 AM](https://user-images.githubusercontent.com/2837257/123462247-e9dc2580-d59e-11eb-8e34-40123f8a36c5.png)

**Comment by superjai** [comment]
Here is a [potential table layout ](https://docs.google.com/spreadsheets/d/1B5mgK2osjdptc5Z7OnvWtTEjIm_9KSBjbSHYttb3kDc/edit#gid=0)to use in documentation.

**Comment by bbest** [comment]
From above, I prefer the **subrows**:


  | marinebon | noaa-onms | noaa-iea
-- | -- | -- | --
builders | infographiqJS | onmsR | plotJS-extra
  | infographiqR |   |  
  | infographiq |   |  
instances |   | cinms | fk-esr-info
  |   | ocnms | ak-info
  |   | sanctsound | indicators-table

**Comment by superjai** [comment]
[Here is the new page of the Infographiq manual](https://marinebon.org/infographiq/organization-of-infographiq-components.html), where the table shown above in this issue is displayed.

**Comment by bbest** [comment]
Looks great Jai, thank you! 🥳
