### ISSUE TITLE
+ docs for plot_function

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/infographiq#48]
see bottom of readme & usage in https://github.com/marinebon/info-demo

**Comment by bbest** [comment]
Right on @7yl4r!

I used [pkgdown](http://pkgdown.r-lib.org/)`::build_site()` to generate `docs/`:

https://marinebon.github.io/infographiq/

Also added a test vignette, which show up under Articles menu. This would be a good place to add details. And move from the info-demo into the R package so it could be considered more standalone.

PS Note, these files moved from the old [`Docs/`] to new `docs/`:

* [_captions.md](https://github.com/marinebon/infographiq/blob/903b01c851e7b5a4d03bd5aca6f389ecde1de7f9/Docs/captions.md)
* [_readme.md](https://github.com/marinebon/infographiq/blob/903b01c851e7b5a4d03bd5aca6f389ecde1de7f9/Docs/readme.md)
