### ISSUE TITLE
getting started with function create_site

### ISSUE THREAD

**Issue by reikopm** [marinebon/infographiq#5]
I'm new to R and GitHub so please excuse my questions if they are naive. It looks to me that the function create_site creates new infographiq *.html for every entry in the csv_indicators.csv file with an entry in the csv_url column.   I don't want to overwrite someone else's infographiq *.html

Am I supposed to edit the csv_indicators.csv to only create infographiq *.htmls for my indicator? And only pull my *.html to github?

I see there is a column in the csv_indicators.csv files for an image, but I don't see that it is used in the create_site code.

Thanks, -Reiko (MBARI)

**Comment by 7yl4r** [comment]
Hi Reiko! We are still working on some better documentation, but it sounds like you have the right idea.

Github, git, and R can be tricky to figure out at first but they are great tools once you get past the initial learning curve. I think what you want to do is "fork" our repository that uses the infographiq package: [info-fk](https://github.com/marinebon/info-fk). This will create a copy of the repository on your github account. 

I have been working to get our [corals infographic](https://marinebon.github.io/info-fk/corals.html) working first so I suggest you look at that one as an example. The README.md and [Docs/Description](https://github.com/marinebon/infographiq/blob/master/Docs/Description.Rmd) have some more information.

**Comment by 7yl4r** [comment]
Since the info-fk repository is getting more complicated, I have created a simple demo infographic repository called [info-demo](https://github.com/USF-IMARS/info-demo). I have also written a very brief overview in the README on that repo.

**Comment by bbest** [comment]
Ok, lots of improvement here by @7yl4r. Thanks for giving this a spin @reikopm and your good questions. I'm going to:

1. Populate the working beginnings for [info-mb](https://github.com/marinebon/info-mb) using Jarrod's [Rockfish Recruitment and Ecosystem Assessment Survey](http://mbon.ioos.us/#module-metadata/8672e1f4-90df-4d9a-8533-37dbea59431e/2b5a4999-286b-4fd5-a4ba-fc3bef82b990) dataset.

1. Update documentation (#22).

1. Screen share with you @reikopm to show how to recreate and iterate.
