### ISSUE TITLE
migrate to authoritative infographiq.js using pkgdown

### ISSUE THREAD

**Issue by bbest** [marinebon/infographiq#56]
## Method

Github Raw is not CORS compliant, eg:

https://raw.githubusercontent.com/marinebon/infographiq/master/inst/js/infographiq.js

Whereas Github Pages is acceptable to load into a different website:

https://marinebon.org/infographiq/infographiq.js

This `/inst/js/infographiq.js` file is published to the `docs/` folder of Github Pages using pkgdown:

```r
pkgdown::build_site()
```

And the `/inst/js/` folder of files is published by having this extra directive in [_pkgdown.yml](https://github.com/marinebon/infographiq/blob/eba51b7370ccb92f884ec717025c0b4ad6c6208b/_pkgdown.yml#L1-L2):

```yaml
template:
  assets: inst/js
```

## TODO

Start versioning infogrpahiq.js,  preferably in sync with 

```r
#  start creating NEWS.md which shows up as Changelog on website
usethis::use_news()

# at every major/minor/patch version increment update version and copy associated JS
usethis::use_version()
```

**Comment by bbest** [comment]
Example R Console sesh w/ @superjai of:

1. `usethis::use_version()` to bump up minor version
2. `pkgdown::build_site()` to update Github Pages in `docs/`

```
> usethis::use_version()
✓ Setting active project to '/Users/bbest/github/infographiq'
There are uncommitted changes and you're about to bump version
Do you want to proceed anyway?

1: Yes
2: Not now
3: No way

Selection: 2
Error: Uncommitted changes. Please commit before continuing.
> usethis::use_version()
Current version is 0.1.3.
Which part to increment? (0 to exit) 

1: major --> 1.0.0
2: minor --> 0.2.0
3: patch --> 0.1.4
4:   dev --> 0.1.3.9000

Selection: 2
✓ Setting Version field in DESCRIPTION to '0.2.0'
✓ Adding new heading to NEWS.md
There are 2 uncommitted files:
* 'DESCRIPTION'
* 'NEWS.md'
Is it ok to commit them?

1: Negative
2: No way
3: I agree

Selection: 3
✓ Adding files
✓ Making a commit with message 'Increment version number'
> pkgdown::build_site()
-- Installing package into temporary library ----------------------------------------
== Building pkgdown site =======================================================
Reading from: '/Users/bbest/github/infographiq'
Writing to:   '/Users/bbest/github/infographiq/docs'
-- Initialising site -----------------------------------------------------------
Copying 'inst/libs/bootstrap-toggle.min.css' to 'bootstrap-toggle.min.css'
Copying 'inst/libs/bootstrap-toggle.min.js' to 'bootstrap-toggle.min.js'
Copying 'inst/libs/d3.v5.min.js' to 'd3.v5.min.js'
Copying 'inst/libs/infographiq.js' to 'infographiq.js'
Copying 'inst/libs/infographiq_v0.1.3.js' to 'infographiq_v0.1.3.js'
Copying 'inst/libs/infographiq_v2019-08-07.js' to 'infographiq_v2019-08-07.js'
Copying 'inst/libs/styles.css' to 'styles.css'
Writing '404.html'
-- Building home ---------------------------------------------------------------
Writing 'authors.html'
Writing 'LICENSE-text.html'
-- Building function reference -------------------------------------------------
Writing 'reference/index.html'
Reading 'man/check_csv_columns.Rd'
Writing 'reference/check_csv_columns.html'
Reading 'man/create_info_site.Rd'
Writing 'reference/create_info_site.html'
Reading 'man/get_plotting_function_brew.Rd'
Writing 'reference/get_plotting_function_brew.html'
Reading 'man/info_svg.Rd'
Writing 'reference/info_svg.html'
Reading 'man/modal_html.Rd'
Writing 'reference/modal_html.html'
Reading 'man/plot_dygraph_timeseries.Rd'
Writing 'reference/plot_dygraph_timeseries.html'
Reading 'man/plot_intertidal_nms.Rd'
Writing 'reference/plot_intertidal_nms.html'
-- Building articles -----------------------------------------------------------
Writing 'articles/index.html'
Reading 'vignettes/captions.Rmd'
Writing 'articles/captions.html'
Reading 'vignettes/plotting_function_call.Rmd'
Writing 'articles/plotting_function_call.html'
Reading 'vignettes/quick-start.Rmd'
Writing 'articles/quick-start.html'
-- Building news ---------------------------------------------------------------
Writing 'news/index.html'
== DONE ========================================================================
Warning message:
Failed to parse example for topic 'get_plotting_function_brew' 
-- Previewing site ------------------------------------------------------------------
Warning message:
In readLines(con) : incomplete final line found on './_pkgdown.yml'
> pkgdown::build_news()
-- Building news --------------------------------------------------------------------
Writing 'news/index.html'
-- Previewing site ------------------------------------------------------------------
```

**Comment by superjai** [comment]
Hey @bbest - the florida keys version of the infographiq javascript/css now is quite different than what is found at the nms4r and infographiq repos.  I find myself confused about where core infographiq functionality ends and where the specifics for the florida keys begin. A few questions:

1. Should "Section" be a required column in the input csv/google sheet for the authoritative version?
2. The modal windows for Florida Keys are generated via columns in the input csv. Should this process be part of the core infographiq process or is it something specific just for the Keys?
3. Related, the csv structure for nms4r is very different than the csv structure for the Keys. 
4. The infographiq implementation for nms4r has a text toggle button while the implementation for the Keys doesn't.

**Comment by superjai** [comment]
hey @bbest - improvements to infographiq functionality:

1. Multiple infographics now possible on same page
2. Section color is now an argument in the function. There is a default color series, but custom colors are possible too (fed into the function as an array). If the number of sections is greater than the number of custom colors, then the colors repeat.

Check out[ this example](https://marinebon.org/fk-esr-info/accordion-test.html).

**Comment by superjai** [comment]
TO DO
[] Toggle text
[] Bullet list vs accordion
[] No section headers
[] Bullet list with section headers
[] Bullet list with section headers and optional background highlighting, eg  
https://sanctsound.ioos.us/draft/s_cinms.html

**Comment by superjai** [comment]
hey @bbest - I have completed the improvements to the infographiq functionality. The lack of highlighting in the svg (which I mentioned in our last conversation) has also been fixed. Check it out [here](https://marinebon.org/fk-esr-info/accordion-test.html).

You'll notice that I didn't use the [bootstrap version of the  toggle button](https://www.bootstraptoggle.com/) for the text on/off and that's because I had great difficulty with getting it to work properly with d3 methods. I instead just used a css-only toggle button.

Infographiq now takes so many potential arguments that a user's manual is definitely needed. On my to-do list.

Before I get to that though, there is a more immediate problem which is that I was unable to use the version of the infographiq javascript and css that I uploaded to the infographiq repo [in this folder](https://github.com/marinebon/infographiq/tree/master/inst/libs/infographiq-v1.0). Instead, I just used an identical version that I copied over to the fk-esr-info repo [here](https://github.com/marinebon/fk-esr-info/tree/main/assets/infographiq-v1.0).

I was thinking that I could solve my issue with accessing the infographiq version of the javascript/css by running pkgdown, but I ran into troubles with that. When I run the function `pkgdown::build_site()` in my local version of the infographiq repo, I get the following output. The trouble seems to be the missing function validate_key, but not sure where that should be coming from. 

```
> pkgdown::build_site()
-- Installing package into temporary library ---------------------------------------------------------
== Building pkgdown site =======================================================
Reading from: 'C:/Users/jaira/OneDrive/Documents/infographiq'
Writing to:   'C:/Users/jaira/OneDrive/Documents/infographiq/docs'
-- Initialising site -----------------------------------------------------------
-- Building home ---------------------------------------------------------------
 namespace 'cachem' is not available and has been replaced
by .GlobalEnv when processing object ''
Error in validate_key(key) : could not find function "validate_key"
Error: callr subprocess failed: could not find function "validate_key"
Type .Last.error.trace to see where the error occured
In addition: Warning message:
In utils::install.packages(pkg$src_path, repos = NULL, type = "source",  :
  installation of package ‘C:/Users/jaira/OneDrive/Documents/infographiq’ had non-zero exit status
> .Last.error.trace

 Stack trace:

 Process 4912:
 1. pkgdown::build_site()
 2. pkgdown:::build_site_external(pkg = pkg, examples = examples,  ...
 3. callr::r(function(..., crayon_enabled, crayon_colors, pkgdown_internet) { ...
 4. callr:::get_result(output = out, options)
 5. throw(newerr, parent = remerr[[2]])

 x callr subprocess failed: could not find function "validate_key" 

 Process 19852:
 17. (function (..., crayon_enabled, crayon_colors, pkgdown_internet)  ...
 18. pkgdown::build_site(...)
 19. pkgdown:::build_site_local(pkg = pkg, examples = examples, run_dont_run = run_dont_run,  ...
 20. pkgdown:::build_home(pkg, override = override, preview = FALSE)
 21. pkgdown:::build_home_index(pkg, quiet = quiet)
 22. pkgdown:::data_home(pkg)
 23. pkgdown:::print_yaml(list(pagetitle = pkg$meta$home[["title"]] %||%  ...
 24. base:::structure(x, class = "print_yaml")
 25. pkgdown:::data_home_sidebar(pkg)
 26. base:::paste0(data_home_sidebar_links(pkg), data_home_sidebar_license(pkg),  ...
 27. pkgdown:::data_home_sidebar_links(pkg)
 28. pkgdown:::cran_link(pkg$package)
 29. encl$`_cache`$get(key)
 30. base:::.handleSimpleError(function (e)  ...
 31. h(simpleError(msg, call))

 x could not find function "validate_key" 
```

**Comment by bbest** [comment]
I presume this is a problem with one of the dependent R packages listed in the DESCRIPTION file, so please try to install this one at a time to try finding the offending R package:

```
Imports: 
    tidyverse,
    brew,
    knitr,
    rmarkdown,
    tools,
    servr,
    dygraphs,
    lubridate,
    stringr,
    xts,
    futile.logger,
    bsplus,
    htmltools,
    r2d3,
    readr
```

**Comment by superjai** [comment]
hey @bbest. Success! Kind of!

Even after going through your suggestions, I could not get pkgdown to work on my pc (not being able to get past the error that I posted above). Thankfully, there is a Mac in the house and I was able to get pkgdown working just fine there. I am going to move the pc-pkgdown problem into its own issue and then close this issue.

I am using the file structure used by [bootstrap](https://getbootstrap.com/). That is, a version folder, which contains js and css folders. Here [is the authoritative version 1.0 in the docs folder](https://github.com/marinebon/infographiq/tree/master/docs/infographiq-v1.0). I included all dependencies in the folders.

My [test page ](https://marinebon.org/fk-esr-info/accordion-test.html) showing all of the infographiq possibilities is now running off of this authoritative version of the code. I will next move the Florida Keys infographic, cinms, and nms4r to this version of the code.

**Comment by bbest** [comment]
Awesome @superjai! 

Please be sure to make any changes to these files under [`inst/libs/`](https://github.com/marinebon/infographiq/tree/master/inst/libs/) since [`docs/`](https://github.com/marinebon/infographiq/tree/master/docs/) gets **deleted** at the start of running:

```r
pkgdown::build_site()
```

**Comment by superjai** [comment]
Yup, that's what I did.
